AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serve academyos.app via Lambda proxying the Webflow products page.

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 128

Resources:
  PublicHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - OPTIONS
        AllowHeaders:
          - "*"

  WebProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.handler
      Description: Proxies Webflow products page for academyos.app traffic.
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref PublicHttpApi
            Path: /
            Method: GET
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref PublicHttpApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiBaseUrl:
    Description: Base URL for the HTTP API
    Value: !Sub "https://${PublicHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
